matrix:
- name: markdown
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8
  language: en_GB
  encoding: utf-8
  dictionary:
    wordlists:
    - .custom-dictionary.txt
  