matrix:
- name: markdown
  pipeline:
  - pyspelling.filters.text
  sources:
  - '**/*.md'
  default_encoding: utf-8
  language: en_GB
  encoding: utf-8
  dictionary:
    wordlists:
    - .custom-dictionary.txt
  