name: On push to master
on:
  push:
    branches: [ "main","master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  call-workflow1:
    uses: ./.github/workflows/update_table_of_contents.yml
  call-workflow2:
    needs: call-workflow1
    uses: ./.github/workflows/render_to_html.yml