name: Deploy changes on Push to Main

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  update-table-of-contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Python Command
        run: python3 migrate_table_of_contents.py

      - name: Use Node.js v16
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0

      - name: Check Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install -g markdown-folder-to-html

      - name: Build HTML
        # execute build_docs.sh
        run: ./build_docs.sh

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Set up Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add README.md && git commit -m "Deployed new changes" || true

      - name: Push changes
        run: | 
          git push origin main || true
