name: Render to HTML

permissions:
  contents: write
  
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Check Node.js version
      run: node -v
    - name: Install dependencies
      run: npm install -g markdown-folder-to-html

    - name: pwd before going one folder back
      run: pwd
    
    - name: Go one folder back and convert to html
      run: |
        cd ..
        markdown-folder-to-html ./potential-projects-ideas
        mv _potential-projects-ideas potential-projects-ideas
        cd potential-projects-ideas
        mv _potential-projects-ideas html

    - name: Set up Git
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add README.md && git commit -m "Rendered into HTML folder" || true
      
    - name: Push changes
      run: | 
        git push origin main || true
    
