name: Render to HTML

permissions:
  contents: write
  
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Check Node.js version
      run: node -v
    - name: Install dependencies
      run: npm install -g markdown-folder-to-html
      
    - name: Make docs folder and move everything in there
      run: mkdir html && mv * ./html || true
      continue-on-error: true

    - name: PWD and ls
      run: pwd && ls
    
    - name: List files in html folder
      run: ls ./html
      
    - name: Render to HTML
      run: markdown-folder-to-html ./html
    - name: Move everything out of the folder
      run: mv ./html/* . && rm -rf ./html
    - name: Rename _html folder to html
      run: mv ./_html ./html

    - name: Set up Git
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add README.md && git commit -m "Rendered into HTML folder" || true
      
    - name: Push changes
      run: | 
        git push origin main || true
    
