name: Render to HTML

permissions:
  contents: write
  
on:
  workflow_call:

jobs:
  render-to-html:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js v16
      uses: actions/setup-node@v1
      with:
        node-version: 16.16.0
    - name: Check Node.js version
      run: node -v
    - name: Install dependencies
      run: npm install -g markdown-folder-to-html

    - name: Build HTML
      run: |
        rm -rf ./html
        mkdir html
        cp -r . ./html || true
        markdown-folder-to-html ./html
        rm -rf ./html
        mv _html html


    - name: Set up Git
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add -f html && git commit -m "Rendered into HTML folder" || true
      
    - name: Push changes
      run: | 
        git push origin main || true
    
