name: Render to HTML

permissions:
  contents: write
  
on:
  push:
    branches:
      - main

jobs:
  render-to-html:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js v16
      uses: actions/setup-node@v1
      with:
        node-version: 16.16.0
    - name: Check Node.js version
      run: node -v
    - name: Install dependencies
      run: npm install -g markdown-folder-to-html
      
    - name: Build HTML
      run: ./build_html.sh

    - name: Set up Git
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add html && git commit -m "Rendered into HTML folder" || true
      
    - name: Push changes
      run: | 
        git push origin main || true
    
