# This workflow will install PySpelling spell checker and its dependencies, then run it

name: Proofread

permissions:
  contents: read
  issues: write
  pull-requests: write
  
on:
  pull_request:
    branches: [ "master","main" ]

jobs:
  spell-check:
    name: Spell check code and documents

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version:  3.8

    - name: Install dependencies
      run: |
        sudo apt-get install --assume-yes aspell aspell-en
        python -m pip install --upgrade pip setuptools
        python -m pip install pyspelling

    - name: Run spell-check
      continue-on-error: true
      run: |
        python -m pyspelling

    # put the results in the comment of the pull request
    - name: Comment on pull request
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## Spell check results
          ```
          ${{ steps.spell-check.outputs.stdout }}
          ```
    # # if the spell check fails, deny the pull request
    # - name: Deny pull request
    #   if: steps.spell-check.outcome == 'failure'
    #   uses: actions/github-script@v3
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     script: |
    #       github.pulls.update({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         pull_number: context.issue.number,
    #         state: 'closed',
    #         maintainer_can_modify: true
    #       })
        