name: Update Table of Contents on Push to Main

permissions:
  contents: write
  
on:
  workflow_call:

jobs:
  update-table-of-contents:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run Python Command
      run: python3 migrate_table_of_contents.py

    - name: Set up Git
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add README.md && git commit -m "Update root README with a new table of contents" || true
      
    - name: Push changes
      run: | 
        git push origin main || true