name: Update Table of Contents on Push to Main

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Python Command
      run: python3 migrate_table_of_contents.py

    - name: Set up Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md && git commit -m "Update root README with a new table of contents"
        git push origin main
